version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: ecowitt-data-prometheus-relay
    binary: ecowitt-data-prometheus-relay
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    flags:
      - -tags=timetzdata
    ldflags:
      - -extldflags "-static"

dockers:
  - id: amd64
    goos: linux
    goarch: amd64
    image_templates:
      - "docker.io/astromechza/ecowitt-data-prometheus-relay:{{ .Tag }}-amd64"
    dockerfile: Dockerfile.release
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"
  - id: arm64
    goos: linux
    goarch: arm64
    image_templates:
      - "docker.io/astromechza/ecowitt-data-prometheus-relay:{{ .Tag }}-arm64"
    dockerfile: Dockerfile.release
    use: buildx
    build_flag_templates:
      - "--platform=linux/arm64"

docker_manifests:
  - name_template: "docker.io/astromechza/ecowitt-data-prometheus-relay:{{ .Tag }}"
    image_templates:
      - "docker.io/astromechza/ecowitt-data-prometheus-relay:{{ .Tag }}-amd64"
      - "docker.io/astromechza/ecowitt-data-prometheus-relay:{{ .Tag }}-arm64"
  - name_template: "docker.io/astromechza/ecowitt-data-prometheus-relay:latest"
    image_templates:
      - "docker.io/astromechza/ecowitt-data-prometheus-relay:{{ .Tag }}-amd64"
      - "docker.io/astromechza/ecowitt-data-prometheus-relay:{{ .Tag }}-arm64"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^chore:"
      - "^ci:"
